import React, { useState, useRef, useEffect } from 'react';
import { useTask } from '../../../contexts/TaskContext';
import { Message, TaskGenerationRequest } from '../../../types/openai';

const ChatSidebar: React.FC = () => {
  const { state, setCurrentTask } = useTask();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: '1',
      role: 'assistant',
      content: 'Hello! I\'m your AI assistant. I can help you create educational tasks, quizzes, and assignments. What would you like to create today?',
      timestamp: new Date(),
    }
  ]);
  const [inputMessage, setInputMessage] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Mock OpenAI service - will be replaced with actual API calls
  const mockOpenAIService = {
    generateTask: async (request: TaskGenerationRequest): Promise<any> => {
      // Simulate API delay
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Return mock task data
      return {
        success: true,
        task: {
          id: `task-${Date.now()}`,
          title: `Generated ${request.taskType || 'Task'}`,
          description: `AI-generated task based on: ${request.prompt}`,
          latexContent: `\\documentclass{article}
\\usepackage{amsmath}
\\begin{document}
\\title{${request.taskType || 'Generated Task'}}
\\author{AI Assistant}
\\date{\\today}

\\maketitle

\\section{Instructions}
${request.prompt}

\\section{Task Content}
This is a sample task generated by AI.

\\end{document}`,
          compiledContent: '',
          version: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
          createdBy: 'ai-assistant',
          status: 'draft' as const,
        },
        latex: '',
        message: 'I\'ve generated a task for you! You can now edit and customize it as needed.',
      };
    },
  };

  const handleSendMessage = async () => {
    if (!inputMessage.trim() || isLoading) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      role: 'user',
      content: inputMessage,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    setInputMessage('');
    setIsLoading(true);

    try {
      // Check if this is a task generation request
      if (inputMessage.toLowerCase().includes('create') || 
          inputMessage.toLowerCase().includes('generate') ||
          inputMessage.toLowerCase().includes('make')) {
        
        const request: TaskGenerationRequest = {
          prompt: inputMessage,
          taskType: 'assignment',
          difficultyLevel: 'intermediate',
          subjectArea: 'general',
        };

        const response = await mockOpenAIService.generateTask(request);
        
        if (response.success) {
          // Add AI response
          const aiMessage: Message = {
            id: (Date.now() + 1).toString(),
            role: 'assistant',
            content: response.message,
            timestamp: new Date(),
            metadata: {
              responseType: 'task_generation',
              taskId: response.task.id,
            },
          };

          setMessages(prev => [...prev, aiMessage]);
          
          // Set the generated task as current task
          setCurrentTask(response.task);
        }
      } else {
        // General chat response
        const aiMessage: Message = {
          id: (Date.now() + 1).toString(),
          role: 'assistant',
          content: `I understand you said: "${inputMessage}". I'm here to help you create educational tasks. Try asking me to "create a math quiz" or "generate an essay prompt" to get started!`,
          timestamp: new Date(),
        };

        setMessages(prev => [...prev, aiMessage]);
      }
    } catch (error) {
      const errorMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: 'Sorry, I encountered an error. Please try again.',
        timestamp: new Date(),
      };

      setMessages(prev => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleQuickAction = (action: string) => {
    const quickActions = {
      'math-quiz': 'Create a math quiz with 5 algebra problems for high school students',
      'essay-prompt': 'Generate an essay prompt about climate change for college students',
      'science-lab': 'Create a science lab worksheet about chemical reactions',
      'history-quiz': 'Generate a history quiz about World War II',
    };

    setInputMessage(quickActions[action as keyof typeof quickActions] || action);
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="p-4 border-b border-gray-200 bg-gray-50">
        <h3 className="text-lg font-semibold text-gray-900">AI Assistant</h3>
        <p className="text-sm text-gray-600">Create tasks with AI help</p>
      </div>

      {/* Quick Actions */}
      <div className="p-4 border-b border-gray-200">
        <h4 className="text-sm font-medium text-gray-700 mb-2">Quick Actions</h4>
        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={() => handleQuickAction('math-quiz')}
            className="px-3 py-2 text-xs bg-blue-100 text-blue-700 rounded-md hover:bg-blue-200 transition-colors"
          >
            Math Quiz
          </button>
          <button
            onClick={() => handleQuickAction('essay-prompt')}
            className="px-3 py-2 text-xs bg-green-100 text-green-700 rounded-md hover:bg-green-200 transition-colors"
          >
            Essay Prompt
          </button>
          <button
            onClick={() => handleQuickAction('science-lab')}
            className="px-3 py-2 text-xs bg-purple-100 text-purple-700 rounded-md hover:bg-purple-200 transition-colors"
          >
            Science Lab
          </button>
          <button
            onClick={() => handleQuickAction('history-quiz')}
            className="px-3 py-2 text-xs bg-orange-100 text-orange-700 rounded-md hover:bg-orange-200 transition-colors"
          >
            History Quiz
          </button>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((message) => (
          <div
            key={message.id}
            className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}
          >
            <div
              className={`max-w-[80%] px-4 py-2 rounded-lg ${
                message.role === 'user'
                  ? 'bg-blue-600 text-white'
                  : 'bg-gray-200 text-gray-800'
              }`}
            >
              <p className="text-sm">{message.content}</p>
              <p className="text-xs opacity-70 mt-1">
                {message.timestamp.toLocaleTimeString()}
              </p>
            </div>
          </div>
        ))}
        
        {isLoading && (
          <div className="flex justify-start">
            <div className="bg-gray-200 text-gray-800 px-4 py-2 rounded-lg">
              <div className="flex items-center space-x-2">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-gray-600"></div>
                <span className="text-sm">AI is thinking...</span>
              </div>
            </div>
          </div>
        )}
        
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-4 border-t border-gray-200">
        <div className="flex space-x-2">
          <input
            type="text"
            value={inputMessage}
            onChange={(e) => setInputMessage(e.target.value)}
            onKeyPress={handleKeyPress}
            placeholder="Ask me to create a task..."
            className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
            disabled={isLoading}
          />
          <button
            onClick={handleSendMessage}
            disabled={!inputMessage.trim() || isLoading}
            className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
};

export default ChatSidebar;
